### ISSUE TITLE
Remove Yahoo Pipes dependancy

### ISSUE THREAD

**Issue by spaetzel** [spaetzel/WatCamp.com#1]
Need to either:
- Parse iCal directly in client side javascript
- Use a different 3rd party service to convert to JSON
- Switch WatCamp.com to have server side processing such as Node

**Comment by pnijjar** [comment]
Since Yahoo pipes is dead maybe this issue is no longer relevant?

**Comment by spaetzel** [comment]
The JavaScript still refers to pipes. that's why the homepage no longer shows any events

**Comment by pnijjar** [comment]
Okay. I found some of those references. I guess I will strip them out?

**Comment by spaetzel** [comment]
Removed the dependancies myself. Put the full calendar embed on the homepage
